### ISSUE TITLE
UpdateSEMSAttributes.pyt throws error if data from SEMS is not a string

### ISSUE THREAD

**Issue by tbock** [USEPA/Superfund-GIS-StarterKit#2]
The script appears to always expect the data from SEMS to be a string and attempts to check the length of everything here: https://github.com/USEPA/Superfund-GIS-StarterKit/blob/f7823e447c3470ba2fc33867f9ac8e11d2b093c9/Scripts/UpdateSEMSAttributes.pyt#L191

This throws `Error - object of type 'int' has no len()` if value is type int.

**Comment by torrin47** [comment]
+1
